name: Auto DevOps

on:
  workflow_dispatch:
    inputs:
      chain-id:
        required: true
        type: string
        description: Name of the new Chain-id
      app_version:
        required: true
        type: string
        description: Celestia App Image Version
      node_version:
        required: true
        type: string
        description: Celestia Node Image Version

jobs:
   argocd-apps:
    permissions:
      contents: write
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: ${{ github.token }}
      TOKEN: ${{ secrets.ACCESS_TOKEN }}
      REPO_NAME: "argocd-apps"
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"
      - name: Print inputs
        run: |
          echo "chain-id: [${{ github.event.inputs.chain-id }}]"
          echo "app_version: [${{ github.event.inputs.app_version }}]"
          echo "node_version: [${{ github.event.inputs.node_version }}]"
      - name: Configure git
        run: |
          git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global user.email "devops@celestia.org"
          git config --global user.name "autodevops"
      - name: Clone Repo
        run: |
          #gh repo clone https://github.com/celestiaorg/argocd-apps
          git clone https://github.com/celestiaorg/${{ env.REPO_NAME }}
      - name: Create the branch
        run: |
          cd ${{ env.REPO_NAME }}
          git checkout -b autodevops/${{ github.event.inputs.chain-id }}
          echo "-----------------------------"
          ls -ltra ./
          echo "chain-id: [${{ github.event.inputs.chain-id }}]"
      - name: Run scripts
        run: |
          cd ${{ env.REPO_NAME }}
          ./scripts/auto_robusta_chain.sh ${{ github.event.inputs.chain-id }}
          echo "-----------------------------"
      - name: Commit & Push the new resources
        run: |
          cd ${{ env.REPO_NAME }}
          git branch
          git add .
          git commit -m "Resources added for the new Chain-id added: [${{ github.event.inputs.chain-id }}]"
          git push origin autodevops/${{ github.event.inputs.chain-id }}
      - name: Authenticate with GitHub
        run: |
          echo "${{ secrets.ACCESS_TOKEN }}" | gh auth login --with-token
      - name: Create pull request
        run: |
          # Create a pull request using GH CLI
          gh pr create --base main --head autodevops/${{ github.event.inputs.chain-id }} --title "AutoDevOps: chain-id -> [${{ github.event.inputs.chain-id }}]" --body "Testing PR"
