name: Auto DevOps

on:
  workflow_dispatch:
    inputs:
      chain-id:
        required: true
        type: string
        description: Name of the new Chain-id
      app_version:
        required: true
        type: string
        description: Celestia App Image Version
      node_version:
        required: true
        type: string
        description: Celestia Node Image Version

jobs:
   argocd-apps:
    permissions:
      contents: write
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: ${{ github.token }}
      TOKEN: ${{ secrets.ACCESS_TOKEN }}
      REPO_NAME: "argocd-apps"
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"
      - name: Print inputs
        run: |
          echo "chain-id: [${{ github.event.inputs.chain-id }}]"
          echo "app_version: [${{ github.event.inputs.app_version }}]"
          echo "node_version: [${{ github.event.inputs.node_version }}]"
      - name: Configure git
        run: |
          git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global user.email "devops@celestia.org"
          git config --global user.name "autodevops"
      - name: Clone Repo
        run: |
          #gh repo clone https://github.com/celestiaorg/argocd-apps
          git clone https://github.com/celestiaorg/${{ env.REPO_NAME }}
      - name: Create the branch
        run: |
          cd ${{ env.REPO_NAME }}
          git checkout -b autodevops/${{ github.event.inputs.chain-id }}
          echo "-----------------------------"
          ls -ltra ./
          echo "chain-id: [${{ github.event.inputs.chain-id }}]"
      - name: Run scripts
        run: |
          cd ${{ env.REPO_NAME }}
          ./scripts/auto_robusta_chain.sh ${{ github.event.inputs.chain-id }}
          echo "-----------------------------"
      - name: Commit & Push the new resources
        run: |
          cd ${{ env.REPO_NAME }}
          git branch
          git add .
          git commit -m "Resources added for the new Chain-id added: [${{ github.event.inputs.chain-id }}]"
          git push origin autodevops/${{ github.event.inputs.chain-id }}
          #- name: Authenticate with GitHub
          #  run: |
          #    echo "${{ env.TOKEN }}" | gh auth login --with-token
          #- name: Create pull request
          #  run: |
          #    # Create a pull request using GH CLI
          #    gh pr create --base main --head autodevops/${{ github.event.inputs.chain-id }} --title "AutoDevOps: chain-id -> [${{ github.event.inputs.chain-id }}]" --body "Testing PR"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.0.4
        continue-on-error: true
        with:
          base: ${{ github.head_ref }}
          token: ${{ secrets.ACCESS_TOKEN }}
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: test
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          signoff: false
          branch: autodevops/${{ github.event.inputs.chain-id }}
          delete-branch: true
          title: test chainid
          body: |
             whatever
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: Resources
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: autodevops/${{ github.event.inputs.chain-id }}
          delete-branch: true
          title: '[Example] Update report'
          body: |
            - Auto-generated by [create-pull-request][1]
          labels: |
            report
            automated pr
          assignees: jrmanes
          reviewers: jrmanes
          team-reviewers: |
            jrmanes
