name: Auto DevOps

on:
  workflow_dispatch:
    inputs:
      chain-id:
        required: true
        type: string
        description: Name of the new Chain-id
      app_version:
        required: true
        type: string
        description: Celestia App Image Version
      node_version:
        required: true
        type: string
        description: Celestia Node Image Version

jobs:
   argocd-apps:
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: ${{ github.token }}
      TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"
      - name: Print inputs
        run: |
          echo "chain-id: [${{ github.event.inputs.chain-id }}]"
          echo "app_version: [${{ github.event.inputs.app_version }}]"
          echo "node_version: [${{ github.event.inputs.node_version }}]"
      - name: Configure git
        run: |
          git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - name: Clone Repo
        run: |
          #gh repo clone https://github.com/celestiaorg/argocd-apps
          git clone https://github.com/celestiaorg/argocd-apps
          cd argocd-apps
          ls -ltra ./
          echo "chain-id: [${{ github.event.inputs.chain-id }}]"
          ./scripts/auto_robusta_chain.sh ${{ github.event.inputs.chain-id }}
          ls -ltra ./overlays/robusta/patches/
