name: AutoGenerate

on:
  workflow_dispatch:
    inputs:
      chain-id:
        required: true
        type: string
        description: Name of the new Chain-id

jobs:
   auto-gen:
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"
      - name: Clone Repo
        run: |
          gh repo clone https://github.com/celestiaorg/argocd-apps.git
          cd argocd-apps
          ls -ltra ./
