name: TestGround Nightly

on:
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '0 0 * * *' # triggered at midnight
  push:
    branches:
      - 'main'

jobs:
  testground:
    #uses: celestiaorg/.github/.github/workflows/reusable_dockerfile_pipeline.yml@v0.1.1 # yamllint disable-line rule:line-length
    uses: jrmanes/.github/.github/workflows/reusable_tg_tests.yaml@main # yamllint disable-line rule:line-length
    with:
      tests_files_path: "compositions/cluster-k8s/sanity/002-da-sync-8.toml"
      testground_url: "${{ secrets.TESTGROUND_URL }}"
      testground_region: "${{ secrets.TESTGROUND_REGION }}"
