name: TestGround Nightly

on:
  push:
    branches:
      - 'main'

env:
  REPO_TG: https://github.com/testground/testground.git
  ORG: celestiaorg
  BRANCH: main
 
jobs:
  prepare-env:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Clone the repo
        run: |
          ls ${{ github.workspace }}
          git clone ${{ env.REPO_TG }}

      - name: Build TestGround
        run: |
          cd testground
          #make goinstall # builds testground and the Docker image, used by the local:docker runner.
          make install # builds testground and the Docker image, used by the local:docker runner.
          ls -ltra ./
          ls -ltra $GOPATH

          #- name: Build TestGround
          #  run: |
          #    cd testground
          #    make install       # builds testground and the Docker image, used by the local:docker runner.
          #    testground -h
          #    testground daemon  # will start the daemon listening on localhost:8042 by default.
          #    #testground plan import --from ./plans/network
          #    #testground run single --plan=network --testcase=ping-pong \
          #    #--builder=docker:go --runner=local:docker \

          #- name: Build TestGround
          #  run: |
          #    cd testground
          #    testground -h

          #- name: Get the latest commit in celestia-node
          #  run: |
          #    apt update; apt install -y jq
          #    CELESTIA_NODE=$(curl -Ls https://api.github.com/repos/${{ env.ORG }}/celestia-node/commits/${{ env.BRANCH }} | jq -c '.sha'| tr -d '"'| cut -c1-7)
          #    echo $CELESTIA_NODE
