name: TestGround Nightly

on:
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '0 0 * * *' # triggered at midnight
  push:
    branches:
      - 'main'

jobs:
  prepare-env:
    runs-on: ubuntu-latest
    outputs:
      testground_url: ${{ steps.testground_url.outputs.test }}
      testground_region: ${{ steps.testground_region.outputs.test }}
    steps:
      - id: testground_url
        run: echo "testground_url=$(echo ${{ secrets.TESTGROUND_URL }})" >> "$GITHUB_OUTPUT"
      - id: testground_region
        run: echo "testground_region=$(echo ${{ secrets.TESTGROUND_REGION }})" >> "$GITHUB_OUTPUT"

  testground:
    needs: prepare-env
    uses: celestiaorg/.github/.github/workflows/reusable_testground_tests.yaml@main # yamllint disable-line rule:line-length
    with:
      tests_files_path: "compositions/cluster-k8s/sanity/002-da-sync-8.toml"
      testground_url: ${{ needs.prepare-env.outputs.testground_url }}"
      testground_region: ${{ needs.prepare-env.outputs.testground_region}}"
